### ISSUE TITLE
Issue importing when 0 files found

### ISSUE THREAD

**Issue by eshu0** [jypelle/mifasol#15]
When running on mac OS X Catalina the client application when importing fails to exit if there are no music files in the folder.
I had one .ogg file and this was skipped and the applications just hung until I killed it via activity monitor.

Once i placed a second file which was .mp3 then it imported and the application exited correctly

Terminal as follows:
./mifasolcli import ~/Documents/music      
Scanning folder "/Users/someuser/Documents/music"
Trying to import 0 songs
Import songs 0 % [-----------------------------------------------------------------------------------------------------------------------------------------------------] 
^CInterruption requested: finishing current file upload before exiting
Import songs 0 % [-----------------------------------------------------------------------------------------------------------------------------------------------------] 
Import songs 0 % [-----------------------------------------------------------------------------------------------------------------------------------------------------] 
Import songs 0 % [-----------------------------------------------------------------------------------------------------------------------------------------------------] 
Import songs 0 % [-----------------------------------------------------------------------------------------------------------------------------------------------------] 
Import songs 0 % [-----------------------------------------------------------------------------------------------------------------------------------------------------]

**Comment by jypelle** [comment]
Hi eshu0

FYI, ogg files are not supported yet (cf https://github.com/jypelle/mifasol#opinionated ), I'm gonna support this format as soon as I find a reliable go library to edit ogg tags.

I will take a look a the void folder issue.
