### ISSUE TITLE
remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by goodforever** [jypelle/mifasol#19]
./mifasolsrv run 

INFO[0000] Creation of mifasol server 0.4.3 ...         
INFO[0000] Updating                                     
INFO[0000] 0 update scripts applied                     
INFO[0000] Starting mifasol server ...                  
INFO[0000] Server listening on https://localhost:6620 using a self-signed certificate 

Chrome browser visit https://localhost:6620  got :

2022/01/16 08:50:14 http: TLS handshake error from [::1]:49265: remote error: tls: unknown certificate
2022/01/16 08:50:14 http: TLS handshake error from [::1]:49267: remote error: tls: unknown certificate

The homepage is waitting at  loading

**Comment by jypelle** [comment]
Hello @goodforever 

Which version of chrome are you using ? 

Are you using Mac/Linux/Windows ?

Could you try with firefox >=96 and chrome >=97 ?

You should accept self-signed certificate in your browser to access the web client.

**Comment by jypelle** [comment]
That's what you should have on first load:

![image](https://user-images.githubusercontent.com/52546084/149665945-a5f49466-46e2-43c2-b8f4-a8e4d5d7d79d.png)

**Comment by chris-skud** [comment]
you could try `chrome://flags/#allow-insecure-localhost` (in the address bar) then restart chrome

**Comment by goodforever** [comment]
@jypelle @chris-skud 
Mac OS Monterey 12.1
Chrome 97.0.4692.71

go version go1.16 darwin/amd64

Allow invalid certificates for resources loaded from localhost.
Allows requests to localhost over HTTPS even when an invalid certificate is presented. – Mac, Windows, Linux, Chrome OS, Android

#allow-insecure-localhost

Enabled

**Comment by jypelle** [comment]
You need go >=1.17

Did you try with the [precompiled binaries](https://github.com/jypelle/mifasol/releases/tag/v0.4.3) ?

**Comment by jypelle** [comment]
Could you send a screenshot of your js console & network tabs when you're loading the homepage ?

**Comment by goodforever** [comment]
I update go to go1.17.6 , there are still errors 
<img width="1280" alt="截屏2022-01-19 22 41 51" src="https://user-images.githubusercontent.com/6078053/150154089-67fa033a-e42d-4e0f-b4f6-804477f13be6.png">
.

**Comment by jypelle** [comment]
Think I got it: https://github.com/jypelle/mifasol/blob/master/Makefile#L21

You should define GOROOT before executing `make release`, I will add this precision in README.md

Is it ok ?

**Comment by goodforever** [comment]
@jypelle Thanks , now OK!
